---
- hosts: ansible-server
  become: false
  tasks:
  - name: building docker image
    command: docker build -t simple-devops-image .
    args:
      chdir: /opt/kubernetes

  - name: tagging docker image to push DockerHub
    command: docker tag simple-devops-image annguyendl/simple-devops-image:latest

  - name: push image to DockerHub - must login first
    command: docker push annguyendl/simple-devops-image:latest

  - name: remove local images
    command: docker rmi simple-devops-image annguyendl/simple-devops-image:latest
    ignore_errors: yes

